# API-first development with OpenAPI
# This file will be used at compile time to generate Spring-MVC endpoint stubs using openapi-generator
openapi: '3.0.1'
info:
  title: 'clinic'
  version: 0.0.1
servers:
  - url: http://localhost:8080/api
    description: Development server
  - url: https://localhost:8080/api
    description: Development server with TLS Profile
paths: {}
components:
  schemas:
    AccountDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
          title: ID
          description: User ID
        login:
          type: string
          title: Login
          description: Login
          pattern: "[a-zA-Z0-9\\._\\-]{3,}"
        firstName:
          type: string
          title: First Name
          description: First Name of user
          maxLength: 50
        lastName:
          type: string
          title: Last Name
          description: First Name of user
          maxLength: 50
        email:
          type: string
          title: E-mail
          format: email
          minLength: 5
          maxLength: 254
        imageUrl:
          type: string
          title: Image URL
          maxLength: 256
        activated:
          type: boolean
        langKey:
          type: string
        createdBy:
          type: string
        createdDate:
          type: string
          format: date-time
        lastModifiedBy:
          type: string
        lastModifiedDate:
          type: string
          format: date-time
        authorities:
          type: array
          uniqueItems: true
          items:
            $ref: '#/components/schemas/Role'
    UserDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
          title: ID
          description: User ID
        login:
          type: string
          title: Login
          description: Login
          pattern: "[a-zA-Z0-9\\._\\-]{3,}"

    Role:
      type: string
      enum:
        - ROLE_USER
        - ROLE_ADMIN

  responses:
    Problem:
      description: error occurred - see status code and problem object for more information.
      content:
        'application/problem+json':
          schema:
            $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'

  securitySchemes:
    jwt:
      type: http
      description: JWT Authentication
      scheme: bearer
      bearerFormat: JWT
    basic:
      type: http
      description: Basic Authentication
      scheme: basic
security:
  - jwt: []
  - basic: []
