### Get All users ( admin only )
GET {{url}}/api/users
Accept: application/json
Authorization: Bearer {{auth_token}}

### Get All users global
GET {{url}}/api/users/list
Accept: application/json
Authorization: Bearer {{auth_token}}

###
